# Generated by Django 5.0.6 on 2025-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_url', models.SlugField(unique=True)),
            ],
        ),
    ]
