# frontend/Dockerfile.prod
FROM node:20 AS build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Serve React build with Nginx ---
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
