# Generated by Django 5.0.6 on 2025-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
