# Generated by Django 5.0.6 on 2025-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
