version: '3.9'

services:
  backend:
    build:
      context: ./backend    # Only watch backend folder for rebuilds
      dockerfile: Dockerfile
    container_name: realestate-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend   # Only watch frontend folder for rebuilds
      dockerfile: Dockerfile
    container_name: realestate-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: realestate-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
