services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media
      - ./frontend/dist:/usr/share/nginx/html  # frontend build output
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
