# Generated by Django 5.0.6 on 2025-09-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_category_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
