# Generated by Django 5.0.6 on 2025-09-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_listed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='listed_date',
        ),
    ]
